apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-container
  template:
    metadata:
      labels:
        app: backend-container
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.backend.env.SPRING_DATASOURCE_URL }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.backend.env.SPRING_DATASOURCE_USERNAME }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.backend.env.SPRING_DATASOURCE_PASSWORD }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-container
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
  selector:
    app: backend-container